# Width of the cli interface
CLI_WIDTH = 130

# Name of the primary log file
LOG_FILE_NAME = 'smartmonitoring_cli-helper.log'

# Name of the update status file
STATUS_FILE_NAME = 'update-status.json'

# Name of the local config file
LOCAL_CONF_FILE_NAME = 'smartmonitoring_config.yaml'

# Name of the Stack file.
DEPLOYED_STACK_FILE_NAME = 'installed_stack.json'

# Text that is printed as Logo
CLI_LOGO_TEXT = "SmartMonitoring by btc."

# Name of this App. Used all over the place in the cli
APP_NAME = "SmartMonitoring-CLI"

# Time in Minutes, after which a "Deploying" status is considered as no longer valid
DEPLOYMENT_REPAIR_TIMEOUT_MINUTES = 10

# Max size of a log file for each container that is generated by docker
CONTAINER_LOG_FILE_SIZE = "500m"


class ConfigDefaults:
    # Default values for the local config file
    LOG_FILE_SIZE_LIMIT_MB = 50  # Max size of the log file in MB
    LOG_FILE_COUNT_LIMIT = 3  # Max number of log files
    ENABLE_DEBUG_LOGGING = False  # Enable debug logging
    UPDATE_CHANNEL = "STABLE"  # Update channel
