SmartMonitoring_Proxy:
  update_channel: STABLE # STABLE / TESTING
  debug_logging: true # Logs as debug if true
  log_file_size_mb: 55 #size of a single log file
  log_file_count: 3 #amount of log files for rotation
  update_manifest_url: https://storage.googleapis.com/btc-public-accessible-data/smartmonitoring_proxies/manifest.yaml

  zabbix_proxy_container:
    proxy_name: MusterAG-Proxy-Buelach
    psk_key_file: /Users/noahcanadea/Dev/zabbix_enc_key.psk

    # With local settings, you can override static configurations from the manifest.
    # A variable specified here takes precedence over the one from the manifest.
    #local_settings:
      #ZBX_DEBUGEVEL: 3

  zabbix_agent_container:
    smartmonitoring_status_file: "/Users/noahcanadea/Documents/GitHub/smartmonitoring/smartmonitoring/temp/update-status.json"

  #zabbix_mysql_container:
    #local_settings:

