# Zabbix base Proxy image
# https://hub.docker.com/r/zabbix/zabbix-proxy-mysql
FROM zabbix/zabbix-proxy-mysql:6.0-ubuntu-latest

# Copy SNMP MIBs to container
WORKDIR /usr/local/share/snmp/mibs/
COPY src/snmp_mibs ./

# Change user to root to install additional packages
USER root

# Copy scripts to container and make them executable
WORKDIR /usr/lib/zabbix/externalscripts/
COPY src/external_scripts/ ./
RUN find /usr/lib/zabbix/externalscripts/ -type f -iname "*.sh" -exec chmod +x {} \; && \
    find /usr/lib/zabbix/externalscripts/ -type f -iname "*.py" -exec chmod +x {} \;

# install python packages defined in requirements.txt
WORKDIR /
COPY requirements.txt ./

# Install required packages and perfrom cleanup
RUN apt-get update && apt-get install -y \
    python3.9 \
    pip \
    && pip install -r requirements.txt --no-cache-dir \
    && rm requirements.txt \
    && apt-get clean  \
    && rm -rf /var/lib/apt/lists/*

# change user back to zabbix (user id based on official zabbix docker file)
USER 1997





