# Zabbix base Proxy MySQL container
# https://hub.docker.com/r/zabbix/zabbix-proxy-mysql
FROM zabbix/zabbix-proxy-mysql:6.0-ubuntu-latest

# Copy SNMP MIBs to container
WORKDIR /usr/local/share/snmp/mibs/
COPY src/snmp_mibs ./

# change user to root
USER root

# copy scripts to container make them executable
WORKDIR /usr/lib/zabbix/externalscripts/
COPY src/external_scripts/ ./



RUN find /usr/lib/zabbix/externalscripts/ -type f -iname "*.sh" -exec chmod +x {} \;
RUN find /usr/lib/zabbix/externalscripts/ -type f -iname "*.py" -exec chmod +x {} \;


# install required packages
RUN apt-get update
RUN apt-get install python3.9 -y && apt-get install pip -y
RUN apt clean


# install python packages
WORKDIR /
COPY requirements.txt ./
RUN pip install -r requirements.txt
RUN rm requirements.txt

# change user to zabbix
USER 1997





